# These are supported funding model platforms

# If you want to support this project, please contact with us: ringotek@RinGoTek.cn Thank you!

github: [fslongjin]
patreon: fslongjin
custom: ['http://asciify.ringotek.cn/donate/']
